In [1]:
import numpy as np


In [10]:
myarry = np.array([[3,6,28,40]],np.int32)
myarry


array([[ 3,  6, 28, 40]])

In [6]:
myarry.shape


(4,)

In [7]:
myarry.dtype

dtype('int32')

In [15]:
myarry[0]

array([ 3,  6, 28, 40])

In [16]:
myarry.shape

(1, 4)

In [17]:
myarry[0,1]

6

In [18]:
myarry[0,1]=74

In [19]:
myarry

array([[ 3, 74, 28, 40]])

In [21]:
myarray = np.array([[[0,1,2],[1,2,3],[2,5,6]]],np.int64)
myarray

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 5, 6]]], dtype=int64)

In [22]:
myarray.dtype


dtype('int64')

In [23]:
myarray.shape

(1, 3, 3)

In [24]:
myarray.size

9

In [34]:
myarray[0,1,2]=42

In [35]:
myarray

array([[[ 0,  1,  2],
        [ 1,  2, 42],
        [ 2,  5,  6]]], dtype=int64)

In [46]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
range= np.arange(15)
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

This is all about numpy

In [49]:
lnspace = np.linspace(2,4,5)
lnspace


array([2. , 2.5, 3. , 3.5, 4. ])

In [50]:
emp = np.empty((2,4))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86920328e-306],
       [1.29060871e-306, 1.42419938e-306, 7.56603881e-307,
        8.34402697e-309]])

In [53]:
ide= np.identity(4)

In [54]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
ide.shape

(4, 4)

In [72]:
rng = np.arange(90)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [99]:
rng=rng.reshape(3,30)
rng

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [74]:
rng.ravel

<function ndarray.ravel>

In [75]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [76]:
myarray

array([[[ 0,  1,  2],
        [ 1,  2, 42],
        [ 2,  5,  6]]], dtype=int64)

In [78]:
myarray.sum(axis=1)

array([[ 3,  8, 50]], dtype=int64)

In [85]:
x =([[1,2,3],[4,5,6],[7,1,0]])

In [86]:
arr = np.array(x)


In [87]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
arr.sum(axis=0)

array([12,  8,  9])

In [90]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [84]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [2, 6, 0]])

In [91]:
arr.flat

In [93]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [94]:
arr.ndim

2

In [95]:
arr.size

9

In [96]:
arr.nbytes

36

In [100]:
arr.argmin()

8

In [101]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [102]:
arr.argmax()

6

In [103]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [104]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [105]:
arr.argmin(axis=0)

array([0, 2, 2], dtype=int64)

Similarly we can do for axis 1.

We can also do matrix addition and multiplication.

In [106]:
arr2 = np.array([[1,2,24],[4,56,6],[7,11,2]])
arr2

array([[ 1,  2, 24],
       [ 4, 56,  6],
       [ 7, 11,  2]])

In [107]:
arr+arr2

array([[ 2,  4, 27],
       [ 8, 61, 12],
       [14, 12,  2]])

In [108]:
arr*arr2

array([[  1,   4,  72],
       [ 16, 280,  36],
       [ 49,  11,   0]])

In [122]:
arr.max()

7

In [123]:
arr.min()

0

In [124]:
arr.sum()

29

In [125]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [126]:
arr.sum(axis=0)

array([12,  8,  9])

In [127]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [128]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [130]:
print(f"python{3+.2}")

python3.2
